---
title: "Developing cell density modeling functions"
author: "Bertille Smith"
date: "Last update 'r Sys.Date()'"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("readxl")
library("ggplot2")
require(dplyr)
library("grid")
source("brewnalysis_functions.R")
library(janitor)
```

## Loadind Data

```{r}
data <- read_excel("brewnalysis_test_data.xlsx") %>%
  janitor::clean_names() %>%
  group_by(brand,batch_number)%>%
  select(brand, batch_number, date,sample_time,dilution_factor,cell_count_1_live_cells,cell_count_1_squares_counted,cell_count_2_live_cells,cell_count_2_squares_counted)


data1 <- sapply(data,function(x) cellcountFuncATB(x))


  #rowwise() %>%
  #mutate(celldensity=cellcountFuncATB(dilution_factor,cell_count_1_live_cells,cell_count_2_live_cells))


#,Tvec=TvecFuncATB(data))

#beer_a_b5 <- data %>%
  #dplyr::filter(brand == "beer_a", batch_number == 5) %>%
  #select(brand, batch_number, date,sample_time,dilution_factor, cell_count_1_live_cells,cell_count_2_live_cells) %>%
  #mutate(beer_a_b5,ACPSS=cell_count_1_live_cells+cell_count_2_live_cells) %>%
 # mutate(beer_a_b5,VSS=0.2*0.2*0.1) %>%
  #mutate (beer_a_b5,cell_density=(ACPSS*dilution_factor)/VSS)




batch1a=data[data$Brand=='beer_a'&data$`Batch Number`=='1',]
batch2a=data[data$Brand=='beer_a'&data$`Batch Number`=='2',]
batch3a=data[data$Brand=='beer_a'&data$`Batch Number`=='3',]
batch4a=data[data$Brand=='beer_a'&data$`Batch Number`=='4',]
batch5a=data[data$Brand=='beer_a'&data$`Batch Number`=='5',]
batch1b=data[data$Brand=='beer_b'&data$`Batch Number`=='1',]
batch2b=data[data$Brand=='beer_b'&data$`Batch Number`=='2',]
batch3b=data[data$Brand=='beer_b'&data$`Batch Number`=='3',]
batch4b=data[data$Brand=='beer_b'&data$`Batch Number`=='4',]
batch5b=data[data$Brand=='beer_b'&data$`Batch Number`=='5',]
batch1c=data[data$Brand=='beer_c'&data$`Batch Number`=='1',]
batch2c=data[data$Brand=='beer_c'&data$`Batch Number`=='2',]
batch3c=data[data$Brand=='beer_c'&data$`Batch Number`=='3',]
batch4c=data[data$Brand=='beer_c'&data$`Batch Number`=='4',]
batch5c=data[data$Brand=='beer_c'&data$`Batch Number`=='5',]
batch1d=data[data$Brand=='beer_d'&data$`Batch Number`=='1',]
batch2d=data[data$Brand=='beer_d'&data$`Batch Number`=='2',]
batch3d=data[data$Brand=='beer_d'&data$`Batch Number`=='3',]
batch4d=data[data$Brand=='beer_d'&data$`Batch Number`=='4',]
batch5d=data[data$Brand=='beer_d'&data$`Batch Number`=='5',]
batch1e=data[data$Brand=='beer_e'&data$`Batch Number`=='1',]
batch2e=data[data$Brand=='beer_e'&data$`Batch Number`=='2',]
batch3e=data[data$Brand=='beer_e'&data$`Batch Number`=='3',]
batch4e=data[data$Brand=='beer_e'&data$`Batch Number`=='4',]
batch5e=data[data$Brand=='beer_e'&data$`Batch Number`=='5',]

Cond1a=ConditionFunc(batch1a)
Cond2a=ConditionFunc(batch2a)
Cond3a=ConditionFunc(batch3a)
Cond4a=ConditionFunc(batch4a)
Cond5a=ConditionFunc(batch5a)
Cond1b=ConditionFunc(batch1b)
Cond2b=ConditionFunc(batch2b)
Cond3b=ConditionFunc(batch3b)
Cond4b=ConditionFunc(batch4b)
Cond5b=ConditionFunc(batch5b)
Cond1c=ConditionFunc(batch1c)
Cond2c=ConditionFunc(batch2c)
Cond3c=ConditionFunc(batch3c)
Cond4c=ConditionFunc(batch4c)
Cond5c=ConditionFunc(batch5c)
Cond1d=ConditionFunc(batch1d)
Cond2d=ConditionFunc(batch2d)
Cond3d=ConditionFunc(batch3d)
Cond4d=ConditionFunc(batch4d)
Cond5d=ConditionFunc(batch5d)
Cond1e=ConditionFunc(batch1e)
Cond2e=ConditionFunc(batch2e)
Cond3e=ConditionFunc(batch3e)
Cond4e=ConditionFunc(batch4e)
Cond5e=ConditionFunc(batch5e)

```

## Visualization of all the batches

```{r}

celldens1a = cellcountFuncATB(batch1a)
celldens2a = cellcountFunc(batch2a)
celldens3a = cellcountFunc(batch3a)
celldens4a = cellcountFunc(batch4a)
celldens5a = cellcountFunc(batch5a)
celldens1b = cellcountFunc(batch1b)
celldens2b = cellcountFunc(batch2b)
celldens3b = cellcountFunc(batch3b)
celldens4b = cellcountFunc(batch4b)
celldens5b = cellcountFunc(batch5b)
celldens1c = cellcountFunc(batch1c)
celldens2c = cellcountFunc(batch2c)
celldens3c = cellcountFunc(batch3c)
celldens4c = cellcountFunc(batch4c)
celldens5c = cellcountFunc(batch5c)
celldens1d = cellcountFunc(batch1d)
celldens2d = cellcountFunc(batch2d)
celldens3d = cellcountFunc(batch3d)
celldens4d = cellcountFunc(batch4d)
celldens5d = cellcountFunc(batch5d)
celldens1e = cellcountFunc(batch1e)
celldens2e = cellcountFunc(batch2e)
celldens3e = cellcountFunc(batch3e)
celldens4e = cellcountFunc(batch4e)
celldens5e = cellcountFunc(batch5e)


celldenstime1a=data.frame(TvecFuncATB(batch1a),celldens1a)
celldenstime2a=data.frame(TvecFuncATB(batch2a),celldens2a)
celldenstime3a=data.frame(TvecFuncATB(batch3a),celldens3a)
celldenstime4a=data.frame(TvecFuncATB(batch4a),celldens4a)
celldenstime5a=data.frame(TvecFuncATB(batch5a),celldens5a)
celldenstime1b=data.frame(TvecFuncATB(batch1b),celldens1b)
celldenstime2b=data.frame(TvecFuncATB(batch2b),celldens2b)
celldenstime3b=data.frame(TvecFuncATB(batch3b),celldens3b)
celldenstime4b=data.frame(TvecFuncATB(batch4b),celldens4b)
celldenstime5b=data.frame(TvecFuncATB(batch5b),celldens5b)
celldenstime1c=data.frame(TvecFuncATB(batch1c),celldens1c)
celldenstime2c=data.frame(TvecFuncATB(batch2c),celldens2c)
celldenstime3c=data.frame(TvecFuncATB(batch3c),celldens3c)
celldenstime4c=data.frame(TvecFuncATB(batch4c),celldens4c)
celldenstime5c=data.frame(TvecFuncATB(batch5c),celldens5c)
celldenstime1d=data.frame(TvecFuncATB(batch1d),celldens1d)
celldenstime2d=data.frame(TvecFuncATB(batch2d),celldens2d)
celldenstime3d=data.frame(TvecFuncATB(batch3d),celldens3d)
celldenstime4d=data.frame(TvecFuncATB(batch4d),celldens4d)
celldenstime5d=data.frame(TvecFuncATB(batch5d),celldens5d)
celldenstime1e=data.frame(TvecFuncATB(batch1e),celldens1e)
celldenstime2e=data.frame(TvecFuncATB(batch2e),celldens2e)
celldenstime3e=data.frame(TvecFuncATB(batch3e),celldens3e)
celldenstime4e=data.frame(TvecFuncATB(batch4e),celldens4e)
celldenstime5e=data.frame(TvecFuncATB(batch5e),celldens5e)

a1<-rep(Cond1a,length(celldens1a))
a2<-rep(Cond2a,length(celldens2a))
a3<-rep(Cond3a,length(celldens3a))
a4<-rep(Cond4a,length(celldens4a))
a5<-rep(Cond5a,length(celldens5a))
b1<-rep(Cond1b,length(celldens1b))
b2<-rep(Cond2b,length(celldens2b))
b3<-rep(Cond3b,length(celldens3b))
b4<-rep(Cond4b,length(celldens4b))
b5<-rep(Cond5b,length(celldens5b))
c1<-rep(Cond1c,length(celldens1c))
c2<-rep(Cond2c,length(celldens2c))
c3<-rep(Cond3c,length(celldens3c))
c4<-rep(Cond4c,length(celldens4c))
c5<-rep(Cond5c,length(celldens5c))
d1<-rep(Cond1d,length(celldens1d))
d2<-rep(Cond2d,length(celldens2d))
d3<-rep(Cond3d,length(celldens3d))
d4<-rep(Cond4d,length(celldens4d))
d5<-rep(Cond5d,length(celldens5d))
e1<-rep(Cond1e,length(celldens1e))
e2<-rep(Cond2e,length(celldens2e))
e3<-rep(Cond3e,length(celldens3e))
e4<-rep(Cond4e,length(celldens4e))
e5<-rep(Cond5e,length(celldens5e))

Tvec<-c(celldenstime1a$TvecFuncATB.batch1a.,celldenstime2a$TvecFuncATB.batch2a.,celldenstime3a$TvecFuncATB.batch3a.,celldenstime4a$TvecFuncATB.batch4a.,celldenstime5a$TvecFuncATB.batch5a.,celldenstime1b$TvecFuncATB.batch1b.,celldenstime2b$TvecFuncATB.batch2b.,celldenstime3b$TvecFuncATB.batch3b.,celldenstime4b$TvecFuncATB.batch4b.,celldenstime5b$TvecFuncATB.batch5b.,celldenstime1c$TvecFuncATB.batch1c.,celldenstime2c$TvecFuncATB.batch2c.,celldenstime3c$TvecFuncATB.batch3c.,celldenstime4c$TvecFuncATB.batch4c.,celldenstime5c$TvecFuncATB.batch5c.,celldenstime1d$TvecFuncATB.batch1d.,celldenstime2d$TvecFuncATB.batch2d.,celldenstime3d$TvecFuncATB.batch3d.,celldenstime4d$TvecFuncATB.batch4d.,celldenstime5d$TvecFuncATB.batch5d.,celldenstime1e$TvecFuncATB.batch1e.,celldenstime2e$TvecFuncATB.batch2e.,celldenstime3e$TvecFuncATB.batch3e.,celldenstime4e$TvecFuncATB.batch4e.,celldenstime5e$TvecFuncATB.batch5e.)
cell.density<-c(celldens1a,celldens2a,celldens3a,celldens4a,celldens5a,celldens1b,celldens2b,celldens3b,celldens4b,celldens5b,celldens1c,celldens2c,celldens3c,celldens4c,celldens5c,celldens1d,celldens2d,celldens3d,celldens4d,celldens5d,celldens1e,celldens2e,celldens3e,celldens4e,celldens5e)
Condition<-c(a1,a2,a3,a4,a5,b1,b2,b3,b4,b5,c1,c2,c3,c4,c5,d1,d2,d3,d4,d5,e1,e2,e3,e4,e5)
DataFinal<-data.frame(Tvec,cell.density,Condition)
DataFinal

plot<- ggplot(data=DataFinal,aes(x=Tvec,y=cell.density))+geom_point(aes(colour = factor(Condition)))+geom_line(aes(colour = factor(Condition)))+labs(title = "Cell density in wort according to fermentation time", x="Fermentation time (hours)",y="Cell density")
plot

```


## Gamma model 


```{r}

#************************Cell density ******************************************
#For this function, the size of the square is set a default value
#The default value length is 0.2 and the default value for the depth is 0.1
#To change these default value type cellcountFunc(data,L="enter the length of 
#the square",D="Enter the depth of the square")

celldens = cellcountFunc(batch2a)

#************************Cell density/time**************************************
celldenstime=TvecFunc(batch2a)

#**********************Fitted data : Gamma model********************************

tvec = celldenstime$Tvec
gamPred = celldenstime$celldens
gamPar <- c(3,15)
fitted<-optim(par=gamPar,fn=gamDevSq,method="Nelder-Mead", tvec=tvec, obs=gamPred)
#fitted

k<-fitted$par[1]
theta<-fitted$par[2]
Pval<-tvec^(k-1)*exp(-tvec/theta)
PVAL<-data.frame(tvec,Pval)
cond<-c("Model data")
PVAL<-data.frame(tvec,Pval,cond)
PVAL

#*************************************Plot**************************************
a<-rep(Cond2a,length(celldens))
b<-rep(cond,length(Pval))

Tvec<-c(tvec,tvec)
cell.density<-c(celldens,Pval)
Condition<-c(a,b)
DataFinal<-data.frame(Tvec,cell.density,Condition)
DataFinal

plot<- ggplot(data=DataFinal,aes(x=Tvec,y=cell.density))+geom_point(aes(colour = factor(Condition)))+geom_line(aes(colour = factor(Condition)))+labs(title = "Cell density in wort according to fermentation time", x="Fermentation time (hours)",y="Cell density")
plot


```

## Gamma + model

```{r}
tvec = celldenstime$Tvec
gamAPred = celldenstime$celldens
gamAPar <- c(1,3,15)  #I put 1 but I didn't know what number to use
fitted<-optim(par=gamAPar,fn=gamADevSq,method="Nelder-Mead", tvec=tvec, obs=gamAPred)

k<-fitted$par[1]
theta<-fitted$par[2]
A<-fitted$par[3]
Pval<- A+tvec^(k-1)*exp(-tvec/theta)
PVAL<-data.frame(tvec,Pval)
cond<-c("Model data")
PVAL<-data.frame(tvec,Pval,cond)

#*************************************Plot**************************************

a<-rep(Cond2a,length(celldens))
b<-rep(cond,length(Pval))

Tvec<-c(tvec,tvec)
cell.density<-c(celldens,Pval)
Condition<-c(a,b)
DataFinal<-data.frame(Tvec,cell.density,Condition)
DataFinal

plot<- ggplot(data=DataFinal,aes(x=Tvec,y=cell.density))+geom_point(aes(colour = factor(Condition)))+geom_line(aes(colour = factor(Condition)))+labs(title = "Cell density in wort according to fermentation time", x="Fermentation time (hours)",y="Cell density")
plot


```


