---
title: "cell_density"
author: "Bertille Smith"
date: "3/5/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library("readxl")
library("ggplot2")
library("grid")
library("janitor")
library("dplyr")

source("../src/brewnalysis_functions_tosend.R")
source("../src/model_functions.R")
source("../src/rss_calculation_functions.R")
source("../src/estimate_parameters.R")

```
## Loading Brewery Data

```{r}
#__________________________________________Import dataset ____________________________________________
#FM
#fermentation_data <- read_excel("~/brewnalysis/brewnalysis/data/brewnalysis_test_data.xlsx") %>%
 # janitor::clean_names() %>% na.omit() %>%
  #dplyr::select(brand, batch_number,fermentation_day,date,sample_time,dilution_factor,cell_count_1_live_cells,cell_count_2_live_cells,cell_count_1_squares_counted,cell_count_2_squares_counted) 



#CCB

fermentation_data <- read_excel("~/brewnalysis/brewnalysis/data/ccb_ale1_tidy_fermdata.xlsx") %>%
  janitor::clean_names() %>% na.omit() %>%
  dplyr::select(brand, 'batch_number'=batch_num,'fermentation_day'=ferm_day,sample_time,cell_count) 
#______________________________________________________________________________________________________




#___________________________________________Run if necessary__________________________________________

#FM : merge the number of cells counted and the number of squares counted into 1 value
#fermentation_data <- dplyr::mutate(fermentation_data,cell_count=cell_count_1_live_cells+cell_count_2_live_cells, square_count=cell_count_1_squares_counted+cell_count_2_squares_counted)

#CCB : convert the cell density unit
fermentation_data <- dplyr::mutate(fermentation_data,'celldensity'=cell_count*10^6)
#______________________________________________________________________________________________________


if (("square_count" %in% colnames(fermentation_data)) & ("cell_count" %in% colnames(fermentation_data)) & ("dilution_factor" %in% colnames(fermentation_data))) {
  fermentation_data <- dplyr::mutate(fermentation_data,celldensity= (data_homog(fermentation_data))) 
} 
```


```{r}

#All the batches

if ("date" %in% colnames(fermentation_data)) {
cell_density=fermentation_data %>% 
  group_by(brand,batch_number) %>% 
  group_map(~ Cell_dens_func_date(.x))
}else{
  cell_density=fermentation_data %>% 
  group_by(brand,batch_number) %>% 
  group_map(~ Cell_dens_func_fermentation_day(.x))
}

cell_density=bind_rows(cell_density)

cell_density=data.frame(cell_density,'brand' = fermentation_data$brand, 'batch_number' = fermentation_data$batch_number) %>%
  dplyr::rename (Tvec= ferment_data.fermentation_day)

  
cell_dens_plot <- ggplot(cell_density, aes(x = Tvec, y = celldensity, group = interaction(brand, batch_number), color = brand)) +
  geom_point() +
  geom_line() +
  labs(title = "Cell density in wort according to fermentation time", x="Fermentation time (hours)",y="Cell density")+
  theme_classic()

```

```{r}
#  Single Batch

#select the brand and batch number you want to see here
single_batch <- fermentation_data %>%
  dplyr::filter(brand == "ale1", batch_number == 1)

if ("date" %in% colnames(single_batch)) {
single_cell_density= Cell_dens_func_date(single_batch)
}else{
  single_cell_density= Cell_dens_func_fermentation_day(single_batch)
}

single_cell_density=data.frame(single_cell_density,'brand' = single_batch$brand, 'batch_number' = single_batch$batch_number)%>%
  dplyr::rename (Tvec= ferment_data.fermentation_day)

single_cell_dens_plot <-ggplot(single_cell_density, aes(x = Tvec, y = celldensity, group = interaction(brand, batch_number), color = interaction(brand))) +
  geom_point() +
  geom_line() +
  labs(title = "Cell density in wort according to fermentation time", x="Fermentation time (hours)",y="Cell density")+
  theme_classic()
```

```{r}
#Plots
cell_dens_plot 
single_cell_dens_plot

```

## ## Fitting the gamma model 

```{r}
gam_guess <- c(3,15)

gam_fits <- cell_density %>%
  group_by(brand, batch_number) %>%
  summarize(gam_pars = est_gam_pars(gam_guess, Tvec, celldensity),
  samp_count = n())


plot_data <- gam_fits %>% left_join(cell_density) %>% rowwise() %>% mutate(gam_pred = gam_func(unlist(gam_pars[1:3]), Tvec)) 
  
  
  # %>% dplyr::select(brand, batch_number,Tvec, gam_pred, cell_density, gam_pars) %>%
 # pivot_longer(c(gravity, log_pred, gen_log_pred,exp_pred), names_to = "model_id", values_to = "specific_gravity")

###gam_pars=est_gam_pars(gam_guess,gam_fits[1],gam_fits[2]) 
####gam_pred=gam_func(unlist(gam_pars),tvec)

#gamma model

Condition_m<-c("Gamma model data")
Condition_e<-c("Empirical data")

cell_density_gamma<-data.frame('Tvec'=plot_data$Tvec,'celldensity'=plot_data$gam_pred,'brand'=plot_data$brand,'batch_number'=plot_data$batch_number,'Condition'=Condition_m)
cell_density_empirical=data.frame(cell_density,'Condition'= Condition_e)
cell_density_gamma_model=bind_rows(cell_density_gamma,cell_density_empirical)

#Plot

all_gamma_plot<- cell_density_gamma %>%
  dplyr::select(Tvec, celldensity,brand, batch_number)%>%
  ggplot(aes(x=Tvec, y=celldensity, group=interaction(brand, batch_number),color=brand))+ 
  geom_line() +
  geom_point()+
  labs(title = "Cell density in wort according to fermentation time (gamma model)", x="Fermentation time (hours)",y="Cell density")+
  theme_classic()


single_gamma_plot_facet_grid<- cell_density_gamma_model %>%
  dplyr::filter(brand == "ale1", batch_number == 5) %>%
  ggplot(aes(x=Tvec, y=celldensity, group=interaction(brand, batch_number,Condition),color=Condition))+
  geom_point() +
  geom_line()+
  labs(title = "Cell density in wort according to fermentation time", x="Fermentation time (hours)",y="Cell density")+
  theme_classic() + facet_grid(~Condition)

single_gamma_plot<- cell_density_gamma_model %>%
  dplyr::filter(brand == "ale1", batch_number == 5) %>%
  ggplot(aes(x=Tvec, y=celldensity, group=interaction(brand, batch_number,Condition),color=Condition))+
  geom_point() +
  geom_line()+
  labs(title = "Cell density in wort according to fermentation time", x="Fermentation time (hours)",y="Cell density")+
  theme_classic()


single_gamma_plot_facet_grid
single_gamma_plot
all_gamma_plot
```


## ## Fitting the gamma + model 

```{r}
gam_a_guess <- c(1,3,15)


gam_a_fits <- cell_density %>%
  group_by(brand, batch_number) %>%
  summarize(gam_a_pars = est_gam_a_pars(gam_a_guess, Tvec, celldensity),
  samp_count = n())

plot_data_a <- gam_a_fits %>% left_join(cell_density) %>% rowwise() %>% mutate(gam_a_pred = gam_a_func(unlist(gam_a_pars[1:4]), Tvec)) 

#gam_a_pars= est_gam_a_pars(gam_a_guess,tvec_a,Obs_a)
#gam_a_pred=gam_a_func(unlist(gam_a_pars),tvec_a)

#gamma + model
Condition_m_a<-c("Gamma + model data")
cell_density_gamma_a<-data.frame('Tvec'=plot_data_a$Tvec,'celldensity'=plot_data_a$gam_a_pred,'brand'=plot_data_a$brand,'batch_number'=plot_data_a$batch_number,'Condition'=Condition_m_a)
cell_density_empirical=data.frame(cell_density,'Condition'= Condition_e)
cell_density_gamma_a_model=bind_rows(cell_density_gamma_a,cell_density_empirical)



#Plot
all_gamma_a_plot<- cell_density_gamma_a %>%
dplyr::select(Tvec, celldensity,brand, batch_number)%>%
ggplot(aes(x=Tvec, y=celldensity, group=interaction(brand, batch_number),color=brand))+ 
  geom_line() +
  geom_point()+
  labs(title = "Cell density in wort according to fermentation time", x="Fermentation time (hours)",y="Cell density")+
  theme_classic()

single_gamma_a_plot_facet_grid<- cell_density_gamma_a_model %>%
  dplyr::filter(brand == "ale1", batch_number == 3) %>%
  ggplot(aes(x=Tvec, y=celldensity, group=interaction(brand, batch_number,Condition),color=Condition))+
  geom_point() +
  geom_line()+
  labs(title = "Cell density in wort according to fermentation time", x="Fermentation time (hours)",y="Cell density")+
  theme_classic()+ facet_grid(~Condition)

single_gamma_a_plot<- cell_density_gamma_a_model %>%
  dplyr::filter(brand == "ale1", batch_number == 3) %>%
  ggplot(aes(x=Tvec, y=celldensity, group=interaction(brand, batch_number,Condition),color=Condition))+
  geom_point() +
  geom_line()+
  labs(title = "Cell density in wort according to fermentation time", x="Fermentation time (hours)",y="Cell density")+
  theme_classic()

single_gamma_a_plot_facet_grid
single_gamma_a_plot
all_gamma_a_plot
```

## ## Cell density and models common plot
```{r}
cell_density_common_model=bind_rows(cell_density_gamma_a,cell_density_empirical,cell_density_gamma)
cell_density_common_plot<- cell_density_common_model %>%
  dplyr::filter(brand == "ale1", batch_number == 2) %>%
  ggplot(aes(x=Tvec, y=celldensity, group=interaction(brand, batch_number,Condition),color=Condition))+
  geom_point() +
  geom_line()+
  labs(title = "Cell density in wort according to fermentation time", x="Fermentation time (hours)",y="Cell density")+
  theme_classic()

cell_density_common_plot_facet_grid<- cell_density_common_model %>%
  dplyr::filter(brand == "ale1", batch_number == 2) %>%
  ggplot(aes(x=Tvec, y=celldensity, group=interaction(brand, batch_number,Condition),color=Condition))+
  geom_point() +
  geom_line()+
  labs(title = "Cell density in wort according to fermentation time", x="Fermentation time (hours)",y="Cell density")+
  theme_classic() + facet_grid(~Condition)

cell_density_common_plot_facet_grid
cell_density_common_plot
```
