---
title: "Developing specific gravity modeling functions"
author: "Arthur Rudolph"
date: "Created Last update `r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)

source("../src/predicted_value_functions.R")
source("../src/rss_calculation_functions.R")
source("../src/estimate_parameters.R")
```

### Loading Brewery Data

```{r}
fermentation_data <- read_excel("../data/brewnalysis_test_data.xlsx") %>%
  janitor::clean_names()

beer_a_b5 <- fermentation_data %>%
  dplyr::filter(brand == "beer_a", batch_number == 5) %>%
  select(brand, batch_number, fermentation_day, gravity, p_h)

grav_plot <- ggplot(fermentation_data, aes(x = fermentation_day, y = gravity, color = brand, shape = factor(batch_number))) +
  geom_point() +
  geom_line()

ph_plot <- ggplot(fermentation_data, aes(x = fermentation_day, y = p_h, color = brand, shape = factor(batch_number))) +
  geom_point() +
  geom_line()

grav_plot
ph_plot

```

### Fitting the specific gravity data to a logistic vs exponential curve

```{r}
tvec <- beer_a_b5$fermentation_day
obs <- beer_a_b5$gravity

log_guess <- c(3, 15, 0, -2) 
log_fit <- optim(par = log_guess, fn = log_rss, method = "Nelder-Mead", tvec = tvec, obs = obs)

gen_log_guess <- c(3, 15, 0, -2, 1) 
gen_log_fit <- optim(par = gen_log_guess, fn = gen_log_rss, method = "Nelder-Mead", tvec = tvec, obs = obs)

exp_guess <- c(max(obs), .5, min(obs))
exp_fit <- optim(par = exp_guess, fn = exp_rss, method = "Nelder-Mead", tvec = tvec, obs = obs)

tvec_max <- max(tvec)
lineVec <- seq(1, max(tvec), by = 1) #times for plotting the predicted values
  
log_pred <- log_func(log_fit$par, tvec)
gen_log_pred <- gen_log_func(gen_log_fit$par, tvec)
exp_pred <- exp_func(exp_fit$par, tvec)


model_fit_plot <- ggplot(beer_a_b5, aes(x = fermentation_day, y = gravity)) +
  geom_point() +
  geom_line() +
  geom_point(aes(x=lineVec, y = log_pred), color = "orange", show.legend = TRUE) +
  geom_line(aes(x=lineVec, y = log_pred), color = "orange") +
  geom_point(aes(x=lineVec, y = gen_log_pred), color = "blue", show.legend = TRUE) +
  geom_line(aes(x=lineVec, y = gen_log_pred), color = "blue") +
  geom_point(aes(x=lineVec, y = exp_pred), color = "green", show.legend = TRUE) +
  geom_line(aes(x=lineVec, y = exp_pred), color = "green") +
  theme_classic()

model_fit_plot
log_fit$par
exp_fit$par




```
### Fitting the exponential and logistic funtion to all data

```{r}
# est_log_pars <- function(log_guess, tvec, obs){
#   log_pars <- optim(par = log_guess, fn = log_rss, method = "Nelder-Mead", tvec = tvec, obs = obs)
#   log_pars <- log_pars$par
#   return(list(log_pars))
#   # return(log_pars)
# }
# 
# est_gen_log_pars <-function(gen_log_guess, tvec, obs){
#   log_pars <- optim(par = gen_log_guess, fn = gen_log_rss, method = "Nelder-Mead", tvec = tvec, obs = obs)
#   log_pars <- log_pars$par
#   return(list(log_pars))
#   # return(log_pars)
# }
# 
# est_exp_pars <- function(exp_guess, tvec, obs){
#   exp_pars <- optim(par = exp_guess, fn = exp_rss, method = "Nelder-Mead", tvec = tvec, obs = obs)
#   exp_pars <- exp_pars$par
#   return(list(exp_pars))
#   # return(exp_pars)
# }
# 
# exp_summary_2 <- function(exp_guess, tvec, obs){
#   exp_pars <- optim(par = exp_guess, fn = exp_dev_sq2, method = "Nelder-Mead", fg = min(obs), tvec = tvec, obs = obs)
#   exp_pars <- exp_pars$par
#   return(list(c(exp_pars, min(obs))))
#   # return(exp_pars)
# }

model_fitsb <- fermentation_data %>%
  # dplyr::filter(brand == "beer_a", batch_number == 1) %>%
  group_by(brand, batch_number) %>%
  summarize(log_pars = est_log_pars(log_guess, fermentation_day, gravity),
            gen_log_pars = est_gen_log_pars(gen_log_guess, fermentation_day, gravity),
            exp_pars = est_exp_pars(exp_guess, fermentation_day, gravity)) %>%
  full_join(fermentation_data) %>%
  mutate(log_pred = log_func(unlist(log_pars), fermentation_day)) %>%
  mutate(gen_log_pred = gen_log_func(unlist(gen_log_pars), fermentation_day)) %>%
  mutate(exp_pred = exp_func(unlist(exp_pars), fermentation_day)) %>%
  pivot_longer(c(gravity, log_pred, gen_log_pred,exp_pred), names_to = "model_id", values_to = "specific_gravity")

density_plot <- model_fits %>% 
  dplyr::filter(brand == "beer_a", batch_number == 1) %>%
  ggplot(aes(x = fermentation_day, y = specific_gravity, group = interaction(brand, batch_number, model_id), color = model_id)) +
  geom_line() +
  geom_point() +
  theme_classic()

density_plot
density_plot + facet_grid(rows = vars(brand), cols = vars(batch_number))
ggsave("../figures/gravity_fits.png", width = 12, height = 12, dpi = 300)

```

