---
title: "cell_density"
author: "Bertille Smith"
date: "3/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(dplyr)

library("readxl")
library("tidyverse")
library("grid")
library("janitor")

source("brewnalysis_functions_tosend.R")

```

## Loading Brewery Data

```{r}
fermentation_data <- read_excel("../data/brewnalysis_test_data.xlsx") %>%
  janitor::clean_names() %>% na.omit()

beer_a_b5 <- fermentation_data %>%
  dplyr::filter(brand == "beer_a", batch_number == 5) %>%
  select(brand, batch_number,date,sample_time,dilution_factor,cell_count_1_live_cells,cell_count_1_squares_counted,cell_count_2_live_cells,cell_count_2_squares_counted)

cell_density=Cell_dens_func(beer_a_b5)
cell_density=data.frame(cell_density,'brand' = beer_a_b5$brand, 'batch_number' = beer_a_b5$batch_number)

#*************************************Plot**************************************

celldens_plot <- ggplot(data=cell_density, aes(x = Tvec, y = celldensity, color = brand, shape = factor(batch_number))) +geom_point() + geom_line()+labs(title = "Cell density in wort according to fermentation time", x="Fermentation time (hours)",y="Cell density")

celldens_plot
```

## ## Gamma model 

```{r}
tvec = cell_density$Tvec
gamPred = cell_density$celldensity
gamPar <- c(3,15)
fitted<-optim(par=gamPar,fn=gamDevSq,method="Nelder-Mead", tvec=tvec, obs=gamPred)


k<-fitted$par[1]
theta<-fitted$par[2]
Pval<-tvec^(k-1)*exp(-tvec/theta)
Condition<-c("Gamma model data")
PVAL<-data.frame(tvec,Pval,Condition)
PVAL

#*************************************Plot**************************************
beer_a_b5$Condition_sample <-paste(beer_a_b5$brand,beer_a_b5$batch_number,sep="_b")
cell_density_gamma=data.frame(cell_density,'Condition_sample'=beer_a_b5$Condition_sample )%>%
  select(Tvec, celldensity,Condition_sample)


Sample_condtion=c(cell_density_gamma$Condition_sample,PVAL$Condition)
cell_density_gamma_model=data.frame(cell_density_gamma,PVAL)%>%
  select(Tvec, celldensity,Condition_sample,Pval,Condition)


Gamma_model_plot<- ggplot(data=cell_density_gamma_model,aes(x=Tvec))+ geom_line(aes(y=celldensity,colour = factor(Condition_sample)))+geom_point(aes(y=celldensity,colour = factor(Condition_sample)))+geom_line(aes(y=Pval,colour = factor(Condition)))+geom_point(aes(y=Pval,colour = factor(Condition)))+labs(title = "Cell density in wort according to fermentation time", x="Fermentation time (hours)",y="Cell density")
Gamma_model_plot

```
## ## Gamma + model 

```{r}
tvec_plus = cell_density$Tvec
gamAPred = cell_density$celldensity
gamAPar <- c(1,3,15)
fittedA<-optim(par=gamAPar,fn=gamADevSq,method="Nelder-Mead", tvec=tvec, obs=gamAPred)


k_plus<-fittedA$par[1]
theta_plus<-fittedA$par[2]
A<-fitted$par[3]
Pval_plus<-A+tvec^(k_plus-1)*exp(-tvec_plus/theta_plus)
Condition_plus<-c("Gamma +model data")
PVAL_plus<-data.frame(tvec_plus,Pval_plus,Condition_plus)
PVAL_plus

#*************************************Plot**************************************
beer_a_b5$Condition_sample <-paste(beer_a_b5$brand,beer_a_b5$batch_number,sep="_b")
cell_density_gamma_plus=data.frame(cell_density,'Condition_sample'=beer_a_b5$Condition_sample )%>%
  select(Tvec, celldensity,Condition_sample)


Sample_condtion_plus=c(cell_density_gamma_plus$Condition_sample,PVAL_plus$Condition_plus)
cell_density_gamma_plus_model=data.frame(cell_density_gamma_plus,PVAL_plus)%>%
  select(Tvec, celldensity,Condition_sample,Pval_plus,Condition_plus)


Gamma_plus_model_plot<- ggplot(data=cell_density_gamma_plus_model,aes(x=Tvec))+ geom_line(aes(y=celldensity,colour = factor(Condition_sample)))+geom_point(aes(y=celldensity,colour = factor(Condition_sample)))+geom_line(aes(y=Pval_plus,colour = factor(Condition_plus)))+geom_point(aes(y=Pval_plus,colour = factor(Condition_plus)))+labs(title = "Cell density in wort according to fermentation time", x="Fermentation time (hours)",y="Cell density")
Gamma_plus_model_plot

```
## ## Cell density and models common plot
```{r}
cell_density_gamma_plus_model%>%
  select(Pval_plus,Condition_plus)
cell_density_models=data.frame(cell_density_gamma_model,cell_density_gamma_plus_model)%>%
  select(Tvec,celldensity, Condition_sample,Pval,Condition,Pval_plus,Condition_plus)
cell_density_models

cell_density_models_plot=ggplot(data=cell_density_models,aes(x=Tvec))+geom_line(aes(y=celldensity,colour = factor(Condition_sample)))+geom_point(aes(y=celldensity,colour = factor(Condition_sample)))+geom_line(aes(y=Pval,colour = factor(Condition)))+geom_point(aes(y=Pval,colour = factor(Condition)))+geom_line(aes(y=Pval_plus,colour = factor(Condition_plus)))+geom_point(aes(y=Pval_plus,colour = factor(Condition_plus)))+labs(title = "Cell density in wort according to fermentation time", x="Fermentation time (hours)",y="Cell density")

cell_density_models_plot

```
